import axios from 'axios';

const {
  REACT_APP_AUTHENTICATION_SERVICE_PORT,
  REACT_APP_AUTHENTICATION_SERVICE_URL,
  REACT_APP_COMMON_DATA_SERVICE_PORT,
  REACT_APP_COMMON_DATA_SERVICE_URL,
  REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT,
  REACT_APP_SEARCH_SUGGESTION_SERVICE_URL,
} = process.env;

export const authApi = axios.create({
  baseURL: REACT_APP_AUTHENTICATION_SERVICE_URL ||`http://localhost:${REACT_APP_AUTHENTICATION_SERVICE_PORT}`,
});

export const commonDataApi = axios.create({
  baseURL: REACT_APP_COMMON_DATA_SERVICE_URL || `http://localhost:${REACT_APP_COMMON_DATA_SERVICE_PORT}`,
});

export const searchSuggestionApi = axios.create({
  baseURL: REACT_APP_SEARCH_SUGGESTION_SERVICE_URL || `http://localhost:${REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT}`,
});