spring.application.name=search-suggestion-service
server.port=8083

cors.allowed-origins: https://shoppers-ecom-app.herokuapp.com,http://localhost:3000
cors.allowed-methods: GET,POST,OPTIONS,DELETE

services.common-data.base-url=http://common-data-service:8082
services.common-data.endpoints.search-suggestion-list=${services.common-data.base-url}/search-suggestion-list