server:
  port: 8083

spring:
  application:
    name: search-suggestion-service

cors:
  allowed-origins: "https://shoppers-ecom-app.herokuapp.com,http://localhost:3000"
  allowed-methods: "GET,POST,OPTIONS,DELETE"

services:
  common-data:
    base-url: http://localhost:8082
    endpoints:
      product-filters-combinations: ${services.common-data.base-url}/product-filters/combinations